Class {
	#name : #XrBlendFactorFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_DST_ALPHA_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_ONE_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_ONE_MINUS_DST_ALPHA_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_SRC_ALPHA_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> XR_BLEND_FACTOR_ZERO_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrBlendFactorFB class >> originalTypeName [

    ^ 'long'
]
