Class {
	#name : #XrBodyJointConfidenceHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBodyJointConfidenceHTC class >> XR_BODY_JOINT_CONFIDENCE_HIGH_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBodyJointConfidenceHTC class >> XR_BODY_JOINT_CONFIDENCE_LOW_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBodyJointConfidenceHTC class >> XR_BODY_JOINT_CONFIDENCE_NONE_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrBodyJointConfidenceHTC class >> originalTypeName [

    ^ 'long'
]
