Class {
	#name : #XrBodyJointSetBD,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBodyJointSetBD class >> XR_BODY_JOINT_SET_BODY_WITHOUT_ARM_BD [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBodyJointSetBD class >> XR_BODY_JOINT_SET_FULL_BODY_JOINTS_BD [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBodyJointSetBD class >> originalTypeName [

    ^ 'long'
]
