Class {
	#name : #XrBodyJointFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_CHEST_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_COUNT_FB [

	^ self on: (70)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_HEAD_FB [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_HIPS_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_ARM_LOWER_FB [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_ARM_UPPER_FB [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_INDEX_DISTAL_FB [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_INDEX_INTERMEDIATE_FB [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_INDEX_METACARPAL_FB [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_INDEX_PROXIMAL_FB [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_INDEX_TIP_FB [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_LITTLE_DISTAL_FB [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_LITTLE_INTERMEDIATE_FB [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_LITTLE_METACARPAL_FB [

	^ self on: (39)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_LITTLE_PROXIMAL_FB [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_LITTLE_TIP_FB [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_MIDDLE_DISTAL_FB [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_MIDDLE_INTERMEDIATE_FB [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_MIDDLE_METACARPAL_FB [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_MIDDLE_PROXIMAL_FB [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_MIDDLE_TIP_FB [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_PALM_FB [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_RING_DISTAL_FB [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_RING_INTERMEDIATE_FB [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_RING_METACARPAL_FB [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_RING_PROXIMAL_FB [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_RING_TIP_FB [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_THUMB_DISTAL_FB [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_THUMB_METACARPAL_FB [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_THUMB_PROXIMAL_FB [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_THUMB_TIP_FB [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_WRIST_FB [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_HAND_WRIST_TWIST_FB [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_SCAPULA_FB [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_LEFT_SHOULDER_FB [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_NECK_FB [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_NONE_FB [

	^ self on: (-1)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_ARM_LOWER_FB [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_ARM_UPPER_FB [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_INDEX_DISTAL_FB [

	^ self on: (53)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_INDEX_INTERMEDIATE_FB [

	^ self on: (52)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_INDEX_METACARPAL_FB [

	^ self on: (50)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_INDEX_PROXIMAL_FB [

	^ self on: (51)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_INDEX_TIP_FB [

	^ self on: (54)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_LITTLE_DISTAL_FB [

	^ self on: (68)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_LITTLE_INTERMEDIATE_FB [

	^ self on: (67)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_LITTLE_METACARPAL_FB [

	^ self on: (65)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_LITTLE_PROXIMAL_FB [

	^ self on: (66)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_LITTLE_TIP_FB [

	^ self on: (69)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_MIDDLE_DISTAL_FB [

	^ self on: (58)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_MIDDLE_INTERMEDIATE_FB [

	^ self on: (57)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_MIDDLE_METACARPAL_FB [

	^ self on: (55)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_MIDDLE_PROXIMAL_FB [

	^ self on: (56)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_MIDDLE_TIP_FB [

	^ self on: (59)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_PALM_FB [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_RING_DISTAL_FB [

	^ self on: (63)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_RING_INTERMEDIATE_FB [

	^ self on: (62)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_RING_METACARPAL_FB [

	^ self on: (60)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_RING_PROXIMAL_FB [

	^ self on: (61)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_RING_TIP_FB [

	^ self on: (64)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_THUMB_DISTAL_FB [

	^ self on: (48)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_THUMB_METACARPAL_FB [

	^ self on: (46)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_THUMB_PROXIMAL_FB [

	^ self on: (47)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_THUMB_TIP_FB [

	^ self on: (49)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_WRIST_FB [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_HAND_WRIST_TWIST_FB [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_SCAPULA_FB [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_RIGHT_SHOULDER_FB [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_ROOT_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_SPINE_LOWER_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_SPINE_MIDDLE_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> XR_BODY_JOINT_SPINE_UPPER_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrBodyJointFB class >> originalTypeName [

    ^ 'long'
]
