Class {
	#name : #XrBodyJointBD,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_HEAD_BD [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_ANKLE_BD [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_COLLAR_BD [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_ELBOW_BD [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_FOOT_BD [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_HAND_BD [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_HIP_BD [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_KNEE_BD [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_SHOULDER_BD [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_LEFT_WRIST_BD [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_NECK_BD [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_PELVIS_BD [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_ANKLE_BD [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_COLLAR_BD [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_ELBOW_BD [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_FOOT_BD [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_HAND_BD [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_HIP_BD [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_KNEE_BD [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_SHOULDER_BD [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_RIGHT_WRIST_BD [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_SPINE1_BD [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_SPINE2_BD [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> XR_BODY_JOINT_SPINE3_BD [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrBodyJointBD class >> originalTypeName [

    ^ 'long'
]
