Class {
	#name : #XrBodyJointHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_CHEST_HTC [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_HEAD_HTC [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_ANKLE_HTC [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_ARM_HTC [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_CLAVICLE_HTC [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_ELBOW_HTC [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_FEET_HTC [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_HIP_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_KNEE_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_SCAPULA_HTC [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_LEFT_WRIST_HTC [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_NECK_HTC [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_PELVIS_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_ANKLE_HTC [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_ARM_HTC [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_CLAVICLE_HTC [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_ELBOW_HTC [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_FEET_HTC [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_HIP_HTC [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_KNEE_HTC [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_SCAPULA_HTC [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_RIGHT_WRIST_HTC [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_SPINE_HIGH_HTC [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_SPINE_LOWER_HTC [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_SPINE_MIDDLE_HTC [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> XR_BODY_JOINT_WAIST_HTC [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrBodyJointHTC class >> originalTypeName [

    ^ 'long'
]
