Class {
	#name : #XrCompositionLayerImageLayoutFlagBitsFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrCompositionLayerImageLayoutFlagBitsFB class >> XR_COMPOSITION_LAYER_IMAGE_LAYOUT_VERTICAL_FLIP_BIT_FB [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrCompositionLayerImageLayoutFlagBitsFB class >> originalTypeName [

    ^ 'long'
]
