Class {
	#name : #XrColorSpaceFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_ADOBE_RGB_FB [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_P3_FB [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_QUEST_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_REC2020_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_REC709_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_RIFT_CV1_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_RIFT_S_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> XR_COLOR_SPACE_UNMANAGED_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrColorSpaceFB class >> originalTypeName [

    ^ 'long'
]
