Class {
	#name : #XrCompareOpFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_ALWAYS_FB [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_EQUAL_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_GREATER_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_GREATER_OR_EQUAL_FB [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_LESS_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_LESS_OR_EQUAL_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_NEVER_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> XR_COMPARE_OP_NOT_EQUAL_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrCompareOpFB class >> originalTypeName [

    ^ 'long'
]
