Class {
	#name : #XrCompositionLayerSpaceWarpInfoFlagBitsFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrCompositionLayerSpaceWarpInfoFlagBitsFB class >> XR_COMPOSITION_LAYER_SPACE_WARP_INFO_FRAME_SKIP_BIT_FB [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrCompositionLayerSpaceWarpInfoFlagBitsFB class >> originalTypeName [

    ^ 'long'
]
