Class {
	#name : #XrDigitalLensControlFlagBitsALMALENCE,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrDigitalLensControlFlagBitsALMALENCE class >> XR_DIGITAL_LENS_CONTROL_PROCESSING_DISABLE_BIT_ALMALENCE [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrDigitalLensControlFlagBitsALMALENCE class >> originalTypeName [

    ^ 'long'
]
