Class {
	#name : #XrEnvironmentBlendMode,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrEnvironmentBlendMode class >> XR_ENVIRONMENT_BLEND_MODE_ADDITIVE [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrEnvironmentBlendMode class >> XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrEnvironmentBlendMode class >> XR_ENVIRONMENT_BLEND_MODE_OPAQUE [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrEnvironmentBlendMode class >> originalTypeName [

    ^ 'long'
]
