Class {
	#name : #XrExternalCameraAttachedToDeviceOCULUS,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrExternalCameraAttachedToDeviceOCULUS class >> XR_EXTERNAL_CAMERA_ATTACHED_TO_DEVICE_HMD_OCULUS [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrExternalCameraAttachedToDeviceOCULUS class >> XR_EXTERNAL_CAMERA_ATTACHED_TO_DEVICE_LTOUCH_OCULUS [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrExternalCameraAttachedToDeviceOCULUS class >> XR_EXTERNAL_CAMERA_ATTACHED_TO_DEVICE_NONE_OCULUS [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrExternalCameraAttachedToDeviceOCULUS class >> XR_EXTERNAL_CAMERA_ATTACHED_TO_DEVICE_RTOUCH_OCULUS [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrExternalCameraAttachedToDeviceOCULUS class >> originalTypeName [

    ^ 'long'
]
