Class {
	#name : #XrEyeExpressionHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_BLINK_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_DOWN_HTC [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_IN_HTC [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_OUT_HTC [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_SQUEEZE_HTC [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_UP_HTC [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_LEFT_WIDE_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_BLINK_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_DOWN_HTC [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_IN_HTC [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_OUT_HTC [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_SQUEEZE_HTC [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_UP_HTC [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> XR_EYE_EXPRESSION_RIGHT_WIDE_HTC [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrEyeExpressionHTC class >> originalTypeName [

    ^ 'long'
]
