Class {
	#name : #XrEyePositionFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrEyePositionFB class >> XR_EYE_POSITION_COUNT_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrEyePositionFB class >> XR_EYE_POSITION_LEFT_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrEyePositionFB class >> XR_EYE_POSITION_RIGHT_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrEyePositionFB class >> originalTypeName [

    ^ 'long'
]
