Class {
	#name : #XrEyeCalibrationStatusML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrEyeCalibrationStatusML class >> XR_EYE_CALIBRATION_STATUS_COARSE_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrEyeCalibrationStatusML class >> XR_EYE_CALIBRATION_STATUS_FINE_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrEyeCalibrationStatusML class >> XR_EYE_CALIBRATION_STATUS_NONE_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrEyeCalibrationStatusML class >> XR_EYE_CALIBRATION_STATUS_UNKNOWN_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrEyeCalibrationStatusML class >> originalTypeName [

    ^ 'long'
]
