Class {
	#name : #XrFacialBlendShapeML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_BROW_LOWERER_L_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_BROW_LOWERER_R_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_CHEEK_RAISER_L_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_CHEEK_RAISER_R_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_CHIN_RAISER_ML [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_DIMPLER_L_ML [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_DIMPLER_R_ML [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_EYES_CLOSED_L_ML [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_EYES_CLOSED_R_ML [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_INNER_BROW_RAISER_L_ML [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_INNER_BROW_RAISER_R_ML [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_JAW_DROP_ML [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LID_TIGHTENER_L_ML [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LID_TIGHTENER_R_ML [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIPS_TOWARD_ML [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_CORNER_DEPRESSOR_L_ML [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_CORNER_DEPRESSOR_R_ML [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_CORNER_PULLER_L_ML [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_CORNER_PULLER_R_ML [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_FUNNELER_LB_ML [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_FUNNELER_LT_ML [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_FUNNELER_RB_ML [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_FUNNELER_RT_ML [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_PRESSOR_L_ML [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_PRESSOR_R_ML [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_PUCKER_L_ML [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_PUCKER_R_ML [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_STRETCHER_L_ML [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_STRETCHER_R_ML [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_SUCK_LB_ML [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_SUCK_LT_ML [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_SUCK_RB_ML [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_SUCK_RT_ML [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_TIGHTENER_L_ML [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LIP_TIGHTENER_R_ML [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LOWER_LIP_DEPRESSOR_L_ML [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_LOWER_LIP_DEPRESSOR_R_ML [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_NOSE_WRINKLER_L_ML [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_NOSE_WRINKLER_R_ML [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_OUTER_BROW_RAISER_L_ML [

	^ self on: (39)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_OUTER_BROW_RAISER_R_ML [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_TONGUE_OUT_ML [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_UPPER_LID_RAISER_L_ML [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_UPPER_LID_RAISER_R_ML [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_UPPER_LIP_RAISER_L_ML [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> XR_FACIAL_BLEND_SHAPE_UPPER_LIP_RAISER_R_ML [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
XrFacialBlendShapeML class >> originalTypeName [

    ^ 'long'
]
