Class {
	#name : #XrFaceExpression2FB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_BROW_LOWERER_L_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_BROW_LOWERER_R_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_PUFF_L_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_PUFF_R_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_RAISER_L_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_RAISER_R_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_SUCK_L_FB [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHEEK_SUCK_R_FB [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHIN_RAISER_B_FB [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_CHIN_RAISER_T_FB [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_COUNT_FB [

	^ self on: (70)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_DIMPLER_L_FB [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_DIMPLER_R_FB [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_CLOSED_L_FB [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_CLOSED_R_FB [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_DOWN_L_FB [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_DOWN_R_FB [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_LEFT_L_FB [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_LEFT_R_FB [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_RIGHT_L_FB [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_RIGHT_R_FB [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_UP_L_FB [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_EYES_LOOK_UP_R_FB [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_INNER_BROW_RAISER_L_FB [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_INNER_BROW_RAISER_R_FB [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_JAW_DROP_FB [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_JAW_SIDEWAYS_LEFT_FB [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_JAW_SIDEWAYS_RIGHT_FB [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_JAW_THRUST_FB [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LID_TIGHTENER_L_FB [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LID_TIGHTENER_R_FB [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIPS_TOWARD_FB [

	^ self on: (50)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_CORNER_DEPRESSOR_L_FB [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_CORNER_DEPRESSOR_R_FB [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_CORNER_PULLER_L_FB [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_CORNER_PULLER_R_FB [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_FUNNELER_LB_FB [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_FUNNELER_LT_FB [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_FUNNELER_RB_FB [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_FUNNELER_RT_FB [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_PRESSOR_L_FB [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_PRESSOR_R_FB [

	^ self on: (39)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_PUCKER_L_FB [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_PUCKER_R_FB [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_STRETCHER_L_FB [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_STRETCHER_R_FB [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_SUCK_LB_FB [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_SUCK_LT_FB [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_SUCK_RB_FB [

	^ self on: (46)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_SUCK_RT_FB [

	^ self on: (47)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_TIGHTENER_L_FB [

	^ self on: (48)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LIP_TIGHTENER_R_FB [

	^ self on: (49)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LOWER_LIP_DEPRESSOR_L_FB [

	^ self on: (51)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_LOWER_LIP_DEPRESSOR_R_FB [

	^ self on: (52)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_MOUTH_LEFT_FB [

	^ self on: (53)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_MOUTH_RIGHT_FB [

	^ self on: (54)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_NOSE_WRINKLER_L_FB [

	^ self on: (55)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_NOSE_WRINKLER_R_FB [

	^ self on: (56)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_OUTER_BROW_RAISER_L_FB [

	^ self on: (57)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_OUTER_BROW_RAISER_R_FB [

	^ self on: (58)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_BACK_DORSAL_VELAR_FB [

	^ self on: (67)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_FRONT_DORSAL_PALATE_FB [

	^ self on: (65)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_MID_DORSAL_PALATE_FB [

	^ self on: (66)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_OUT_FB [

	^ self on: (68)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_RETREAT_FB [

	^ self on: (69)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_TIP_ALVEOLAR_FB [

	^ self on: (64)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_TONGUE_TIP_INTERDENTAL_FB [

	^ self on: (63)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_UPPER_LID_RAISER_L_FB [

	^ self on: (59)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_UPPER_LID_RAISER_R_FB [

	^ self on: (60)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_UPPER_LIP_RAISER_L_FB [

	^ self on: (61)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> XR_FACE_EXPRESSION2_UPPER_LIP_RAISER_R_FB [

	^ self on: (62)
]

{ #category : #'as yet unclassified' }
XrFaceExpression2FB class >> originalTypeName [

    ^ 'long'
]
