Class {
	#name : #XrFaceTrackingDataSource2FB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFaceTrackingDataSource2FB class >> XR_FACE_TRACKING_DATA_SOURCE2_AUDIO_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFaceTrackingDataSource2FB class >> XR_FACE_TRACKING_DATA_SOURCE2_VISUAL_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFaceTrackingDataSource2FB class >> originalTypeName [

    ^ 'long'
]
