Class {
	#name : #XrFaceConfidence2FB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFaceConfidence2FB class >> XR_FACE_CONFIDENCE2_COUNT_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFaceConfidence2FB class >> XR_FACE_CONFIDENCE2_LOWER_FACE_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFaceConfidence2FB class >> XR_FACE_CONFIDENCE2_UPPER_FACE_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFaceConfidence2FB class >> originalTypeName [

    ^ 'long'
]
