Class {
	#name : #XrFaceConfidenceFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFaceConfidenceFB class >> XR_FACE_CONFIDENCE_COUNT_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFaceConfidenceFB class >> XR_FACE_CONFIDENCE_LOWER_FACE_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFaceConfidenceFB class >> XR_FACE_CONFIDENCE_UPPER_FACE_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFaceConfidenceFB class >> originalTypeName [

    ^ 'long'
]
