Class {
	#name : #XrFacialTrackingTypeHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFacialTrackingTypeHTC class >> XR_FACIAL_TRACKING_TYPE_EYE_DEFAULT_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFacialTrackingTypeHTC class >> XR_FACIAL_TRACKING_TYPE_LIP_DEFAULT_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFacialTrackingTypeHTC class >> originalTypeName [

    ^ 'long'
]
