Class {
	#name : #XrFoveationEyeTrackedStateFlagBitsMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFoveationEyeTrackedStateFlagBitsMETA class >> XR_FOVEATION_EYE_TRACKED_STATE_VALID_BIT_META [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrFoveationEyeTrackedStateFlagBitsMETA class >> originalTypeName [

    ^ 'long'
]
