Class {
	#name : #XrFoveationLevelFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFoveationLevelFB class >> XR_FOVEATION_LEVEL_HIGH_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelFB class >> XR_FOVEATION_LEVEL_LOW_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelFB class >> XR_FOVEATION_LEVEL_MEDIUM_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelFB class >> XR_FOVEATION_LEVEL_NONE_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelFB class >> originalTypeName [

    ^ 'long'
]
