Class {
	#name : #XrFoveationLevelHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFoveationLevelHTC class >> XR_FOVEATION_LEVEL_HIGH_HTC [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelHTC class >> XR_FOVEATION_LEVEL_LOW_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelHTC class >> XR_FOVEATION_LEVEL_MEDIUM_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelHTC class >> XR_FOVEATION_LEVEL_NONE_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFoveationLevelHTC class >> originalTypeName [

    ^ 'long'
]
