Class {
	#name : #XrForceFeedbackCurlLocationMNDX,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> XR_FORCE_FEEDBACK_CURL_LOCATION_INDEX_CURL_MNDX [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> XR_FORCE_FEEDBACK_CURL_LOCATION_LITTLE_CURL_MNDX [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> XR_FORCE_FEEDBACK_CURL_LOCATION_MIDDLE_CURL_MNDX [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> XR_FORCE_FEEDBACK_CURL_LOCATION_RING_CURL_MNDX [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> XR_FORCE_FEEDBACK_CURL_LOCATION_THUMB_CURL_MNDX [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrForceFeedbackCurlLocationMNDX class >> originalTypeName [

    ^ 'long'
]
