Class {
	#name : #XrFoveationDynamicFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFoveationDynamicFB class >> XR_FOVEATION_DYNAMIC_DISABLED_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFoveationDynamicFB class >> XR_FOVEATION_DYNAMIC_LEVEL_ENABLED_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFoveationDynamicFB class >> originalTypeName [

    ^ 'long'
]
