Class {
	#name : #XrFoveationModeHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFoveationModeHTC class >> XR_FOVEATION_MODE_CUSTOM_HTC [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrFoveationModeHTC class >> XR_FOVEATION_MODE_DISABLE_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrFoveationModeHTC class >> XR_FOVEATION_MODE_DYNAMIC_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFoveationModeHTC class >> XR_FOVEATION_MODE_FIXED_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFoveationModeHTC class >> originalTypeName [

    ^ 'long'
]
