Class {
	#name : #XrFutureStateEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrFutureStateEXT class >> XR_FUTURE_STATE_PENDING_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrFutureStateEXT class >> XR_FUTURE_STATE_READY_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrFutureStateEXT class >> originalTypeName [

    ^ 'long'
]
