Class {
	#name : #XrGlobalDimmerFrameEndInfoFlagBitsML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrGlobalDimmerFrameEndInfoFlagBitsML class >> XR_GLOBAL_DIMMER_FRAME_END_INFO_ENABLED_BIT_ML [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrGlobalDimmerFrameEndInfoFlagBitsML class >> originalTypeName [

    ^ 'long'
]
