Class {
	#name : #XrHandPoseTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandPoseTypeMSFT class >> XR_HAND_POSE_TYPE_REFERENCE_OPEN_PALM_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrHandPoseTypeMSFT class >> XR_HAND_POSE_TYPE_TRACKED_MSFT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrHandPoseTypeMSFT class >> originalTypeName [

    ^ 'long'
]
