Class {
	#name : #XrHandJointsMotionRangeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandJointsMotionRangeEXT class >> XR_HAND_JOINTS_MOTION_RANGE_CONFORMING_TO_CONTROLLER_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrHandJointsMotionRangeEXT class >> XR_HAND_JOINTS_MOTION_RANGE_UNOBSTRUCTED_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrHandJointsMotionRangeEXT class >> originalTypeName [

    ^ 'long'
]
