Class {
	#name : #XrHandTrackingAimFlagBitsFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_COMPUTED_BIT_FB [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_DOMINANT_HAND_BIT_FB [

	^ self on: (1 bitShift: 7)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_INDEX_PINCHING_BIT_FB [

	^ self on: (1 bitShift: 2)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_LITTLE_PINCHING_BIT_FB [

	^ self on: (1 bitShift: 5)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_MENU_PRESSED_BIT_FB [

	^ self on: (1 bitShift: 8)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_MIDDLE_PINCHING_BIT_FB [

	^ self on: (1 bitShift: 3)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_RING_PINCHING_BIT_FB [

	^ self on: (1 bitShift: 4)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_SYSTEM_GESTURE_BIT_FB [

	^ self on: (1 bitShift: 6)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> XR_HAND_TRACKING_AIM_VALID_BIT_FB [

	^ self on: (1 bitShift: 1)
]

{ #category : #'as yet unclassified' }
XrHandTrackingAimFlagBitsFB class >> originalTypeName [

    ^ 'long'
]
