Class {
	#name : #XrHandJointSetEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandJointSetEXT class >> XR_HAND_JOINT_SET_DEFAULT_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrHandJointSetEXT class >> XR_HAND_JOINT_SET_HAND_WITH_FOREARM_ULTRALEAP [

	^ self on: (1000149000)
]

{ #category : #'as yet unclassified' }
XrHandJointSetEXT class >> originalTypeName [

    ^ 'long'
]
