Class {
	#name : #XrHandForearmJointULTRALEAP,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_ELBOW_ULTRALEAP [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_INDEX_DISTAL_ULTRALEAP [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_INDEX_INTERMEDIATE_ULTRALEAP [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_INDEX_METACARPAL_ULTRALEAP [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_INDEX_PROXIMAL_ULTRALEAP [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_INDEX_TIP_ULTRALEAP [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_LITTLE_DISTAL_ULTRALEAP [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_LITTLE_INTERMEDIATE_ULTRALEAP [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_LITTLE_METACARPAL_ULTRALEAP [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_LITTLE_PROXIMAL_ULTRALEAP [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_LITTLE_TIP_ULTRALEAP [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_MIDDLE_DISTAL_ULTRALEAP [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_MIDDLE_INTERMEDIATE_ULTRALEAP [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_MIDDLE_METACARPAL_ULTRALEAP [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_MIDDLE_PROXIMAL_ULTRALEAP [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_MIDDLE_TIP_ULTRALEAP [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_PALM_ULTRALEAP [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_RING_DISTAL_ULTRALEAP [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_RING_INTERMEDIATE_ULTRALEAP [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_RING_METACARPAL_ULTRALEAP [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_RING_PROXIMAL_ULTRALEAP [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_RING_TIP_ULTRALEAP [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_THUMB_DISTAL_ULTRALEAP [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_THUMB_METACARPAL_ULTRALEAP [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_THUMB_PROXIMAL_ULTRALEAP [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_THUMB_TIP_ULTRALEAP [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> XR_HAND_FOREARM_JOINT_WRIST_ULTRALEAP [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrHandForearmJointULTRALEAP class >> originalTypeName [

    ^ 'long'
]
