Class {
	#name : #XrHandTrackingDataSourceEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandTrackingDataSourceEXT class >> XR_HAND_TRACKING_DATA_SOURCE_CONTROLLER_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrHandTrackingDataSourceEXT class >> XR_HAND_TRACKING_DATA_SOURCE_UNOBSTRUCTED_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrHandTrackingDataSourceEXT class >> originalTypeName [

    ^ 'long'
]
