Class {
	#name : #XrHandJointEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_INDEX_DISTAL_EXT [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_INDEX_METACARPAL_EXT [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_INDEX_PROXIMAL_EXT [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_INDEX_TIP_EXT [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_LITTLE_DISTAL_EXT [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_LITTLE_INTERMEDIATE_EXT [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_LITTLE_METACARPAL_EXT [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_LITTLE_PROXIMAL_EXT [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_LITTLE_TIP_EXT [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_MIDDLE_DISTAL_EXT [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_MIDDLE_METACARPAL_EXT [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_MIDDLE_TIP_EXT [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_PALM_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_RING_DISTAL_EXT [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_RING_INTERMEDIATE_EXT [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_RING_METACARPAL_EXT [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_RING_PROXIMAL_EXT [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_RING_TIP_EXT [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_THUMB_DISTAL_EXT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_THUMB_METACARPAL_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_THUMB_PROXIMAL_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_THUMB_TIP_EXT [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> XR_HAND_JOINT_WRIST_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrHandJointEXT class >> originalTypeName [

    ^ 'long'
]
