Class {
	#name : #XrLipExpressionHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_CHEEK_PUFF_LEFT_HTC [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_CHEEK_PUFF_RIGHT_HTC [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_CHEEK_SUCK_HTC [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_JAW_FORWARD_HTC [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_JAW_LEFT_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_JAW_OPEN_HTC [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_JAW_RIGHT_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_APE_SHAPE_HTC [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNLEFT_HTC [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_DOWNRIGHT_HTC [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_INSIDE_HTC [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_LEFT_HTC [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_OVERLAY_HTC [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_OVERTURN_HTC [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_LOWER_RIGHT_HTC [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_POUT_HTC [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_RAISER_LEFT_HTC [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_RAISER_RIGHT_HTC [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_SAD_LEFT_HTC [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_SAD_RIGHT_HTC [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_SMILE_LEFT_HTC [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_SMILE_RIGHT_HTC [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_STRETCHER_LEFT_HTC [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_STRETCHER_RIGHT_HTC [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_INSIDE_HTC [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_LEFT_HTC [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_OVERTURN_HTC [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_RIGHT_HTC [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_UPLEFT_HTC [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_MOUTH_UPPER_UPRIGHT_HTC [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_DOWNLEFT_MORPH_HTC [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_DOWNRIGHT_MORPH_HTC [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_DOWN_HTC [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_LEFT_HTC [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_LONGSTEP1_HTC [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_LONGSTEP2_HTC [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_RIGHT_HTC [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_ROLL_HTC [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_UPLEFT_MORPH_HTC [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_UPRIGHT_MORPH_HTC [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> XR_LIP_EXPRESSION_TONGUE_UP_HTC [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
XrLipExpressionHTC class >> originalTypeName [

    ^ 'long'
]
