Class {
	#name : #XrLocalizationMapStateML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrLocalizationMapStateML class >> XR_LOCALIZATION_MAP_STATE_LOCALIZATION_PENDING_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapStateML class >> XR_LOCALIZATION_MAP_STATE_LOCALIZATION_SLEEPING_BEFORE_RETRY_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapStateML class >> XR_LOCALIZATION_MAP_STATE_LOCALIZED_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapStateML class >> XR_LOCALIZATION_MAP_STATE_NOT_LOCALIZED_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapStateML class >> originalTypeName [

    ^ 'long'
]
