Class {
	#name : #XrLocalDimmingModeMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrLocalDimmingModeMETA class >> XR_LOCAL_DIMMING_MODE_OFF_META [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrLocalDimmingModeMETA class >> XR_LOCAL_DIMMING_MODE_ON_META [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrLocalDimmingModeMETA class >> originalTypeName [

    ^ 'long'
]
