Class {
	#name : #XrLoaderInterfaceStructs,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_API_LAYER_CREATE_INFO [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_API_LAYER_NEXT_INFO [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_API_LAYER_REQUEST [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_LOADER_INFO [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_RUNTIME_REQUEST [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> XR_LOADER_INTERFACE_STRUCT_UNINTIALIZED [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrLoaderInterfaceStructs class >> originalTypeName [

    ^ 'long'
]
