Class {
	#name : #XrLocalizationMapTypeML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrLocalizationMapTypeML class >> XR_LOCALIZATION_MAP_TYPE_CLOUD_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapTypeML class >> XR_LOCALIZATION_MAP_TYPE_ON_DEVICE_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrLocalizationMapTypeML class >> originalTypeName [

    ^ 'long'
]
