Class {
	#name : #XrMarkerDetectorStatusML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorStatusML class >> XR_MARKER_DETECTOR_STATUS_ERROR_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorStatusML class >> XR_MARKER_DETECTOR_STATUS_PENDING_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorStatusML class >> XR_MARKER_DETECTOR_STATUS_READY_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorStatusML class >> originalTypeName [

    ^ 'long'
]
