Class {
	#name : #XrMarkerTypeML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_APRIL_TAG_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_ARUCO_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_CODE_128_ML [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_EAN_13_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_QR_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> XR_MARKER_TYPE_UPC_A_ML [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrMarkerTypeML class >> originalTypeName [

    ^ 'long'
]
