Class {
	#name : #XrMarkerDetectorCameraML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorCameraML class >> XR_MARKER_DETECTOR_CAMERA_RGB_CAMERA_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCameraML class >> XR_MARKER_DETECTOR_CAMERA_WORLD_CAMERAS_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCameraML class >> originalTypeName [

    ^ 'long'
]
