Class {
	#name : #XrMarkerDetectorCornerRefineMethodML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorCornerRefineMethodML class >> XR_MARKER_DETECTOR_CORNER_REFINE_METHOD_APRIL_TAG_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCornerRefineMethodML class >> XR_MARKER_DETECTOR_CORNER_REFINE_METHOD_CONTOUR_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCornerRefineMethodML class >> XR_MARKER_DETECTOR_CORNER_REFINE_METHOD_NONE_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCornerRefineMethodML class >> XR_MARKER_DETECTOR_CORNER_REFINE_METHOD_SUBPIX_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorCornerRefineMethodML class >> originalTypeName [

    ^ 'long'
]
