Class {
	#name : #XrMarkerArucoDictML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_4X4_1000_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_4X4_100_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_4X4_250_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_4X4_50_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_5X5_1000_ML [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_5X5_100_ML [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_5X5_250_ML [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_5X5_50_ML [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_6X6_1000_ML [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_6X6_100_ML [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_6X6_250_ML [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_6X6_50_ML [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_7X7_1000_ML [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_7X7_100_ML [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_7X7_250_ML [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> XR_MARKER_ARUCO_DICT_7X7_50_ML [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrMarkerArucoDictML class >> originalTypeName [

    ^ 'long'
]
