Class {
	#name : #XrMarkerDetectorFullAnalysisIntervalML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorFullAnalysisIntervalML class >> XR_MARKER_DETECTOR_FULL_ANALYSIS_INTERVAL_FAST_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFullAnalysisIntervalML class >> XR_MARKER_DETECTOR_FULL_ANALYSIS_INTERVAL_MAX_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFullAnalysisIntervalML class >> XR_MARKER_DETECTOR_FULL_ANALYSIS_INTERVAL_MEDIUM_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFullAnalysisIntervalML class >> XR_MARKER_DETECTOR_FULL_ANALYSIS_INTERVAL_SLOW_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFullAnalysisIntervalML class >> originalTypeName [

    ^ 'long'
]
