Class {
	#name : #XrMarkerDetectorProfileML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_ACCURACY_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_CUSTOM_ML [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_DEFAULT_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_LARGE_FOV_ML [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_SMALL_TARGETS_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> XR_MARKER_DETECTOR_PROFILE_SPEED_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorProfileML class >> originalTypeName [

    ^ 'long'
]
