Class {
	#name : #XrMarkerDetectorFpsML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorFpsML class >> XR_MARKER_DETECTOR_FPS_HIGH_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFpsML class >> XR_MARKER_DETECTOR_FPS_LOW_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFpsML class >> XR_MARKER_DETECTOR_FPS_MAX_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFpsML class >> XR_MARKER_DETECTOR_FPS_MEDIUM_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorFpsML class >> originalTypeName [

    ^ 'long'
]
