Class {
	#name : #XrMarkerAprilTagDictML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerAprilTagDictML class >> XR_MARKER_APRIL_TAG_DICT_16H5_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerAprilTagDictML class >> XR_MARKER_APRIL_TAG_DICT_25H9_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerAprilTagDictML class >> XR_MARKER_APRIL_TAG_DICT_36H10_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerAprilTagDictML class >> XR_MARKER_APRIL_TAG_DICT_36H11_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMarkerAprilTagDictML class >> originalTypeName [

    ^ 'long'
]
