Class {
	#name : #XrMarkerDetectorResolutionML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMarkerDetectorResolutionML class >> XR_MARKER_DETECTOR_RESOLUTION_HIGH_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorResolutionML class >> XR_MARKER_DETECTOR_RESOLUTION_LOW_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorResolutionML class >> XR_MARKER_DETECTOR_RESOLUTION_MEDIUM_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMarkerDetectorResolutionML class >> originalTypeName [

    ^ 'long'
]
