Class {
	#name : #XrMeshComputeLodMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrMeshComputeLodMSFT class >> XR_MESH_COMPUTE_LOD_COARSE_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrMeshComputeLodMSFT class >> XR_MESH_COMPUTE_LOD_FINE_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrMeshComputeLodMSFT class >> XR_MESH_COMPUTE_LOD_MEDIUM_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrMeshComputeLodMSFT class >> XR_MESH_COMPUTE_LOD_UNLIMITED_MSFT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrMeshComputeLodMSFT class >> originalTypeName [

    ^ 'long'
]
