Class {
	#name : #XrObjectType,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_ACTION [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_ACTION_SET [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_BODY_TRACKER_BD [

	^ self on: (1000385000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_BODY_TRACKER_FB [

	^ self on: (1000076000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_BODY_TRACKER_HTC [

	^ self on: (1000320000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT [

	^ self on: (1000019000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_ENVIRONMENT_DEPTH_PROVIDER_META [

	^ self on: (1000291000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_META [

	^ self on: (1000291001)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_EXPORTED_LOCALIZATION_MAP_ML [

	^ self on: (1000139000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_EYE_TRACKER_FB [

	^ self on: (1000202000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_FACE_TRACKER2_FB [

	^ self on: (1000287012)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_FACE_TRACKER_FB [

	^ self on: (1000201000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_FACIAL_EXPRESSION_CLIENT_ML [

	^ self on: (1000482000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_FACIAL_TRACKER_HTC [

	^ self on: (1000104000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_FOVEATION_PROFILE_FB [

	^ self on: (1000114000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_GEOMETRY_INSTANCE_FB [

	^ self on: (1000118004)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_HAND_TRACKER_EXT [

	^ self on: (1000051000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_INSTANCE [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_MARKER_DETECTOR_ML [

	^ self on: (1000138000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_PASSTHROUGH_COLOR_LUT_META [

	^ self on: (1000266000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_PASSTHROUGH_FB [

	^ self on: (1000118000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_PASSTHROUGH_HTC [

	^ self on: (1000317000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_PASSTHROUGH_LAYER_FB [

	^ self on: (1000118002)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_PLANE_DETECTOR_EXT [

	^ self on: (1000429000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SCENE_MSFT [

	^ self on: (1000097001)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SCENE_OBSERVER_MSFT [

	^ self on: (1000097000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SESSION [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPACE [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPACE_USER_FB [

	^ self on: (1000241000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPATIAL_ANCHORS_STORAGE_ML [

	^ self on: (1000141000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPATIAL_ANCHOR_MSFT [

	^ self on: (1000039000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPATIAL_ANCHOR_STORE_CONNECTION_MSFT [

	^ self on: (1000142000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SPATIAL_GRAPH_NODE_BINDING_MSFT [

	^ self on: (1000049000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_SWAPCHAIN [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_TRIANGLE_MESH_FB [

	^ self on: (1000117000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_UNKNOWN [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_VIRTUAL_KEYBOARD_META [

	^ self on: (1000219000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> XR_OBJECT_TYPE_WORLD_MESH_DETECTOR_ML [

	^ self on: (1000474000)
]

{ #category : #'as yet unclassified' }
XrObjectType class >> originalTypeName [

    ^ 'long'
]
