Class {
	#name : #XrOverlayMainSessionFlagBitsEXTX,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrOverlayMainSessionFlagBitsEXTX class >> XR_OVERLAY_MAIN_SESSION_ENABLED_COMPOSITION_LAYER_INFO_DEPTH_BIT_EXTX [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrOverlayMainSessionFlagBitsEXTX class >> originalTypeName [

    ^ 'long'
]
