Class {
	#name : #XrPassthroughPreferenceFlagBitsMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPassthroughPreferenceFlagBitsMETA class >> XR_PASSTHROUGH_PREFERENCE_DEFAULT_TO_ACTIVE_BIT_META [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrPassthroughPreferenceFlagBitsMETA class >> originalTypeName [

    ^ 'long'
]
