Class {
	#name : #XrPassthroughLayerPurposeFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPassthroughLayerPurposeFB class >> XR_PASSTHROUGH_LAYER_PURPOSE_PROJECTED_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPassthroughLayerPurposeFB class >> XR_PASSTHROUGH_LAYER_PURPOSE_RECONSTRUCTION_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPassthroughLayerPurposeFB class >> XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_HANDS_FB [

	^ self on: (1000203001)
]

{ #category : #'as yet unclassified' }
XrPassthroughLayerPurposeFB class >> XR_PASSTHROUGH_LAYER_PURPOSE_TRACKED_KEYBOARD_MASKED_HANDS_FB [

	^ self on: (1000203002)
]

{ #category : #'as yet unclassified' }
XrPassthroughLayerPurposeFB class >> originalTypeName [

    ^ 'long'
]
