Class {
	#name : #XrPassthroughFormHTC,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPassthroughFormHTC class >> XR_PASSTHROUGH_FORM_PLANAR_HTC [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPassthroughFormHTC class >> XR_PASSTHROUGH_FORM_PROJECTED_HTC [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPassthroughFormHTC class >> originalTypeName [

    ^ 'long'
]
