Class {
	#name : #XrPassthroughColorLutChannelsMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPassthroughColorLutChannelsMETA class >> XR_PASSTHROUGH_COLOR_LUT_CHANNELS_RGBA_META [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPassthroughColorLutChannelsMETA class >> XR_PASSTHROUGH_COLOR_LUT_CHANNELS_RGB_META [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPassthroughColorLutChannelsMETA class >> originalTypeName [

    ^ 'long'
]
