Class {
	#name : #XrPerfSettingsLevelEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPerfSettingsLevelEXT class >> XR_PERF_SETTINGS_LEVEL_BOOST_EXT [

	^ self on: (75)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsLevelEXT class >> XR_PERF_SETTINGS_LEVEL_POWER_SAVINGS_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsLevelEXT class >> XR_PERF_SETTINGS_LEVEL_SUSTAINED_HIGH_EXT [

	^ self on: (50)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsLevelEXT class >> XR_PERF_SETTINGS_LEVEL_SUSTAINED_LOW_EXT [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsLevelEXT class >> originalTypeName [

    ^ 'long'
]
