Class {
	#name : #XrPerformanceMetricsCounterUnitMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> XR_PERFORMANCE_METRICS_COUNTER_UNIT_BYTES_META [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> XR_PERFORMANCE_METRICS_COUNTER_UNIT_GENERIC_META [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> XR_PERFORMANCE_METRICS_COUNTER_UNIT_HERTZ_META [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> XR_PERFORMANCE_METRICS_COUNTER_UNIT_MILLISECONDS_META [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> XR_PERFORMANCE_METRICS_COUNTER_UNIT_PERCENTAGE_META [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPerformanceMetricsCounterUnitMETA class >> originalTypeName [

    ^ 'long'
]
