Class {
	#name : #XrPerfSettingsSubDomainEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPerfSettingsSubDomainEXT class >> XR_PERF_SETTINGS_SUB_DOMAIN_COMPOSITING_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsSubDomainEXT class >> XR_PERF_SETTINGS_SUB_DOMAIN_RENDERING_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsSubDomainEXT class >> XR_PERF_SETTINGS_SUB_DOMAIN_THERMAL_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsSubDomainEXT class >> originalTypeName [

    ^ 'long'
]
