Class {
	#name : #XrPerfSettingsNotificationLevelEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPerfSettingsNotificationLevelEXT class >> XR_PERF_SETTINGS_NOTIF_LEVEL_IMPAIRED_EXT [

	^ self on: (75)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsNotificationLevelEXT class >> XR_PERF_SETTINGS_NOTIF_LEVEL_NORMAL_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsNotificationLevelEXT class >> XR_PERF_SETTINGS_NOTIF_LEVEL_WARNING_EXT [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsNotificationLevelEXT class >> originalTypeName [

    ^ 'long'
]
