Class {
	#name : #XrPerfSettingsDomainEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPerfSettingsDomainEXT class >> XR_PERF_SETTINGS_DOMAIN_CPU_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsDomainEXT class >> XR_PERF_SETTINGS_DOMAIN_GPU_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPerfSettingsDomainEXT class >> originalTypeName [

    ^ 'long'
]
