Class {
	#name : #XrPlaneDetectionStateEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> XR_PLANE_DETECTION_STATE_DONE_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> XR_PLANE_DETECTION_STATE_ERROR_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> XR_PLANE_DETECTION_STATE_FATAL_EXT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> XR_PLANE_DETECTION_STATE_NONE_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> XR_PLANE_DETECTION_STATE_PENDING_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectionStateEXT class >> originalTypeName [

    ^ 'long'
]
