Class {
	#name : #XrPlaneDetectorOrientationEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPlaneDetectorOrientationEXT class >> XR_PLANE_DETECTOR_ORIENTATION_ARBITRARY_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorOrientationEXT class >> XR_PLANE_DETECTOR_ORIENTATION_HORIZONTAL_DOWNWARD_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorOrientationEXT class >> XR_PLANE_DETECTOR_ORIENTATION_HORIZONTAL_UPWARD_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorOrientationEXT class >> XR_PLANE_DETECTOR_ORIENTATION_VERTICAL_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorOrientationEXT class >> originalTypeName [

    ^ 'long'
]
