Class {
	#name : #XrPlaneDetectorSemanticTypeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> XR_PLANE_DETECTOR_SEMANTIC_TYPE_CEILING_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> XR_PLANE_DETECTOR_SEMANTIC_TYPE_FLOOR_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> XR_PLANE_DETECTOR_SEMANTIC_TYPE_PLATFORM_EXT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> XR_PLANE_DETECTOR_SEMANTIC_TYPE_UNDEFINED_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> XR_PLANE_DETECTOR_SEMANTIC_TYPE_WALL_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrPlaneDetectorSemanticTypeEXT class >> originalTypeName [

    ^ 'long'
]
