Class {
	#name : #XrReprojectionModeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrReprojectionModeMSFT class >> XR_REPROJECTION_MODE_DEPTH_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrReprojectionModeMSFT class >> XR_REPROJECTION_MODE_ORIENTATION_ONLY_MSFT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrReprojectionModeMSFT class >> XR_REPROJECTION_MODE_PLANAR_FROM_DEPTH_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrReprojectionModeMSFT class >> XR_REPROJECTION_MODE_PLANAR_MANUAL_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrReprojectionModeMSFT class >> originalTypeName [

    ^ 'long'
]
