Class {
	#name : #XrResult,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrResult class >> XR_COLOCATION_DISCOVERY_ALREADY_ADVERTISING_META [

	^ self on: (1000571003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_COLOCATION_DISCOVERY_ALREADY_DISCOVERING_META [

	^ self on: (1000571004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ENVIRONMENT_DEPTH_NOT_AVAILABLE_META [

	^ self on: (1000291000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ACTIONSETS_ALREADY_ATTACHED [

	^ self on: (-47)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ACTIONSET_NOT_ATTACHED [

	^ self on: (-46)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ACTION_TYPE_MISMATCH [

	^ self on: (-27)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR [

	^ self on: (-1000003001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR [

	^ self on: (-1000003000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_API_LAYER_NOT_PRESENT [

	^ self on: (-36)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_API_VERSION_UNSUPPORTED [

	^ self on: (-4)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_CALL_ORDER_INVALID [

	^ self on: (-37)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_COLOCATION_DISCOVERY_NETWORK_FAILED_META [

	^ self on: (-1000571001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_COLOCATION_DISCOVERY_NO_DISCOVERY_METHOD_META [

	^ self on: (-1000571002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB [

	^ self on: (-1000108000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT [

	^ self on: (-1000097000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT [

	^ self on: (-1000055000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT [

	^ self on: (-1000039001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB [

	^ self on: (-1000101000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED [

	^ self on: (-42)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_EXTENSION_NOT_PRESENT [

	^ self on: (-9)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FACIAL_EXPRESSION_PERMISSION_DENIED_ML [

	^ self on: (1000482000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB [

	^ self on: (-1000118001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB [

	^ self on: (-1000118002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FEATURE_UNSUPPORTED [

	^ self on: (-8)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FILE_ACCESS_ERROR [

	^ self on: (-32)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FILE_CONTENTS_INVALID [

	^ self on: (-33)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FORM_FACTOR_UNAVAILABLE [

	^ self on: (-35)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FORM_FACTOR_UNSUPPORTED [

	^ self on: (-34)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FUNCTION_UNSUPPORTED [

	^ self on: (-7)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FUTURE_INVALID_EXT [

	^ self on: (-1000469002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_FUTURE_PENDING_EXT [

	^ self on: (-1000469001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_GRAPHICS_DEVICE_INVALID [

	^ self on: (-38)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING [

	^ self on: (-50)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_HANDLE_INVALID [

	^ self on: (-12)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_HINT_ALREADY_SET_QCOM [

	^ self on: (-1000306000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_INDEX_OUT_OF_RANGE [

	^ self on: (-40)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_INITIALIZATION_FAILED [

	^ self on: (-6)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_INSTANCE_LOST [

	^ self on: (-13)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB [

	^ self on: (-1000118004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LAYER_INVALID [

	^ self on: (-23)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LAYER_LIMIT_EXCEEDED [

	^ self on: (-24)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LIMIT_REACHED [

	^ self on: (-10)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML [

	^ self on: (-1000139005)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML [

	^ self on: (-1000139006)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_FAIL_ML [

	^ self on: (-1000139002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML [

	^ self on: (-1000139003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML [

	^ self on: (-1000139000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML [

	^ self on: (-1000139004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML [

	^ self on: (-1000139001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZED_NAME_DUPLICATED [

	^ self on: (-48)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_LOCALIZED_NAME_INVALID [

	^ self on: (-49)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML [

	^ self on: (-1000138003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML [

	^ self on: (-1000138002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML [

	^ self on: (-1000138001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML [

	^ self on: (-1000138000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_ID_INVALID_VARJO [

	^ self on: (-1000124001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_INVALID_ML [

	^ self on: (-1000138004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_MARKER_NOT_TRACKED_VARJO [

	^ self on: (-1000124000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_NAME_DUPLICATED [

	^ self on: (-44)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_NAME_INVALID [

	^ self on: (-45)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_NOT_AN_ANCHOR_HTC [

	^ self on: (-1000319000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB [

	^ self on: (-1000118003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_OUT_OF_MEMORY [

	^ self on: (-3)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META [

	^ self on: (-1000266000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PATH_COUNT_EXCEEDED [

	^ self on: (-20)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PATH_FORMAT_INVALID [

	^ self on: (-21)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PATH_INVALID [

	^ self on: (-19)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PATH_UNSUPPORTED [

	^ self on: (-22)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PERMISSION_INSUFFICIENT_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT [

	^ self on: (-1000429001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_POSE_INVALID [

	^ self on: (-39)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_REFERENCE_SPACE_UNSUPPORTED [

	^ self on: (-31)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_RENDER_MODEL_KEY_INVALID_FB [

	^ self on: (-1000119000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT [

	^ self on: (-1000066000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_RUNTIME_FAILURE [

	^ self on: (-2)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_RUNTIME_UNAVAILABLE [

	^ self on: (-51)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT [

	^ self on: (-1000097001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT [

	^ self on: (-1000097002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT [

	^ self on: (-1000097005)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT [

	^ self on: (-1000097004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT [

	^ self on: (-1000097003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT [

	^ self on: (-1000053000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SESSION_LOST [

	^ self on: (-17)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SESSION_NOT_READY [

	^ self on: (-28)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SESSION_NOT_RUNNING [

	^ self on: (-16)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SESSION_NOT_STOPPING [

	^ self on: (-29)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SESSION_RUNNING [

	^ self on: (-14)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SIZE_INSUFFICIENT [

	^ self on: (-11)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB [

	^ self on: (-1000169004)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB [

	^ self on: (-1000113001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB [

	^ self on: (-1000113000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB [

	^ self on: (-1000113003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB [

	^ self on: (-1000113002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_GROUP_NOT_FOUND_META [

	^ self on: (-1000572002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_LOCALIZATION_FAILED_FB [

	^ self on: (-1000169001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB [

	^ self on: (-1000169000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB [

	^ self on: (-1000169003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_NETWORK_TIMEOUT_FB [

	^ self on: (-1000169002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPACE_NOT_LOCATABLE_EXT [

	^ self on: (-1000429000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHORS_ANCHOR_NOT_FOUND_ML [

	^ self on: (-1000141000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHORS_NOT_LOCALIZED_ML [

	^ self on: (-1000140001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHORS_OUT_OF_MAP_BOUNDS_ML [

	^ self on: (-1000140002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHORS_PERMISSION_DENIED_ML [

	^ self on: (-1000140000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHORS_SPACE_NOT_LOCATABLE_ML [

	^ self on: (-1000140003)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT [

	^ self on: (-1000142002)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT [

	^ self on: (-1000142001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED [

	^ self on: (-26)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SWAPCHAIN_RECT_INVALID [

	^ self on: (-25)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SYSTEM_INVALID [

	^ self on: (-18)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SYSTEM_NOTIFICATION_INCOMPATIBLE_SKU_ML [

	^ self on: (-1000473001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_SYSTEM_NOTIFICATION_PERMISSION_DENIED_ML [

	^ self on: (-1000473000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_TIME_INVALID [

	^ self on: (-30)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB [

	^ self on: (-1000118000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_UNKNOWN_PASSTHROUGH_FB [

	^ self on: (-1000118050)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_VALIDATION_FAILURE [

	^ self on: (-1)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED [

	^ self on: (-41)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_WORLD_MESH_DETECTOR_PERMISSION_DENIED_ML [

	^ self on: (-1000474000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_ERROR_WORLD_MESH_DETECTOR_SPACE_NOT_LOCATABLE_ML [

	^ self on: (-1000474001)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_EVENT_UNAVAILABLE [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_FRAME_DISCARDED [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_RENDER_MODEL_UNAVAILABLE_FB [

	^ self on: (1000119020)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_SCENE_MARKER_DATA_NOT_STRING_MSFT [

	^ self on: (1000147000)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_SESSION_LOSS_PENDING [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_SESSION_NOT_FOCUSED [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_SPACE_BOUNDS_UNAVAILABLE [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_SUCCESS [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrResult class >> XR_TIMEOUT_EXPIRED [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrResult class >> originalTypeName [

    ^ 'long'
]
