Class {
	#name : #XrReferenceSpaceType,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO [

	^ self on: (1000121000)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_LOCAL [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_LOCALIZATION_MAP_ML [

	^ self on: (1000139000)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_STAGE [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT [

	^ self on: (1000038000)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> XR_REFERENCE_SPACE_TYPE_VIEW [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrReferenceSpaceType class >> originalTypeName [

    ^ 'long'
]
