Class {
	#name : #XrSceneComputeStateMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneComputeStateMSFT class >> XR_SCENE_COMPUTE_STATE_COMPLETED_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneComputeStateMSFT class >> XR_SCENE_COMPUTE_STATE_COMPLETED_WITH_ERROR_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSceneComputeStateMSFT class >> XR_SCENE_COMPUTE_STATE_NONE_MSFT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrSceneComputeStateMSFT class >> XR_SCENE_COMPUTE_STATE_UPDATING_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneComputeStateMSFT class >> originalTypeName [

    ^ 'long'
]
