Class {
	#name : #XrSceneObjectTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_BACKGROUND_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_CEILING_MSFT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_FLOOR_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_INFERRED_MSFT [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_PLATFORM_MSFT [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_UNCATEGORIZED_MSFT [

	^ self on: (-1)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> XR_SCENE_OBJECT_TYPE_WALL_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneObjectTypeMSFT class >> originalTypeName [

    ^ 'long'
]
