Class {
	#name : #XrSceneComputeConsistencyMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneComputeConsistencyMSFT class >> XR_SCENE_COMPUTE_CONSISTENCY_OCCLUSION_OPTIMIZED_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSceneComputeConsistencyMSFT class >> XR_SCENE_COMPUTE_CONSISTENCY_SNAPSHOT_COMPLETE_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneComputeConsistencyMSFT class >> XR_SCENE_COMPUTE_CONSISTENCY_SNAPSHOT_INCOMPLETE_FAST_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneComputeConsistencyMSFT class >> originalTypeName [

    ^ 'long'
]
