Class {
	#name : #XrSceneComponentTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_COLLIDER_MESH_MSFT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_INVALID_MSFT [

	^ self on: (-1)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_MARKER_MSFT [

	^ self on: (1000147000)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_OBJECT_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_PLANE_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_SERIALIZED_SCENE_FRAGMENT_MSFT [

	^ self on: (1000098000)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> XR_SCENE_COMPONENT_TYPE_VISUAL_MESH_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSceneComponentTypeMSFT class >> originalTypeName [

    ^ 'long'
]
