Class {
	#name : #XrScenePlaneAlignmentTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrScenePlaneAlignmentTypeMSFT class >> XR_SCENE_PLANE_ALIGNMENT_TYPE_HORIZONTAL_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrScenePlaneAlignmentTypeMSFT class >> XR_SCENE_PLANE_ALIGNMENT_TYPE_NON_ORTHOGONAL_MSFT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrScenePlaneAlignmentTypeMSFT class >> XR_SCENE_PLANE_ALIGNMENT_TYPE_VERTICAL_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrScenePlaneAlignmentTypeMSFT class >> originalTypeName [

    ^ 'long'
]
