Class {
	#name : #XrSceneMarkerQRCodeSymbolTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneMarkerQRCodeSymbolTypeMSFT class >> XR_SCENE_MARKER_QR_CODE_SYMBOL_TYPE_MICRO_QR_CODE_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneMarkerQRCodeSymbolTypeMSFT class >> XR_SCENE_MARKER_QR_CODE_SYMBOL_TYPE_QR_CODE_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneMarkerQRCodeSymbolTypeMSFT class >> originalTypeName [

    ^ 'long'
]
