Class {
	#name : #XrSceneComputeFeatureMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_COLLIDER_MESH_MSFT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_MARKER_MSFT [

	^ self on: (1000147000)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_PLANE_MESH_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_PLANE_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_SERIALIZE_SCENE_MSFT [

	^ self on: (1000098000)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> XR_SCENE_COMPUTE_FEATURE_VISUAL_MESH_MSFT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSceneComputeFeatureMSFT class >> originalTypeName [

    ^ 'long'
]
