Class {
	#name : #XrSpatialGraphNodeTypeMSFT,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSpatialGraphNodeTypeMSFT class >> XR_SPATIAL_GRAPH_NODE_TYPE_DYNAMIC_MSFT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSpatialGraphNodeTypeMSFT class >> XR_SPATIAL_GRAPH_NODE_TYPE_STATIC_MSFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSpatialGraphNodeTypeMSFT class >> originalTypeName [

    ^ 'long'
]
