Class {
	#name : #XrSpatialAnchorConfidenceML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSpatialAnchorConfidenceML class >> XR_SPATIAL_ANCHOR_CONFIDENCE_HIGH_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSpatialAnchorConfidenceML class >> XR_SPATIAL_ANCHOR_CONFIDENCE_LOW_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrSpatialAnchorConfidenceML class >> XR_SPATIAL_ANCHOR_CONFIDENCE_MEDIUM_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSpatialAnchorConfidenceML class >> originalTypeName [

    ^ 'long'
]
