Class {
	#name : #XrSpaceStorageLocationFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSpaceStorageLocationFB class >> XR_SPACE_STORAGE_LOCATION_CLOUD_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSpaceStorageLocationFB class >> XR_SPACE_STORAGE_LOCATION_INVALID_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrSpaceStorageLocationFB class >> XR_SPACE_STORAGE_LOCATION_LOCAL_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSpaceStorageLocationFB class >> originalTypeName [

    ^ 'long'
]
