Class {
	#name : #XrSpaceComponentTypeFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_BOUNDED_2D_FB [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_BOUNDED_3D_FB [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_LOCATABLE_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_ROOM_LAYOUT_FB [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_SEMANTIC_LABELS_FB [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_SHARABLE_FB [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_SPACE_CONTAINER_FB [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_STORABLE_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> XR_SPACE_COMPONENT_TYPE_TRIANGLE_MESH_META [

	^ self on: (1000269000)
]

{ #category : #'as yet unclassified' }
XrSpaceComponentTypeFB class >> originalTypeName [

    ^ 'long'
]
