Class {
	#name : #XrSpacePersistenceModeFB,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrSpacePersistenceModeFB class >> XR_SPACE_PERSISTENCE_MODE_INDEFINITE_FB [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrSpacePersistenceModeFB class >> XR_SPACE_PERSISTENCE_MODE_INVALID_FB [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrSpacePersistenceModeFB class >> originalTypeName [

    ^ 'long'
]
