Class {
	#name : #XrStructureType,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTIONS_SYNC_INFO [

	^ self on: (61)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_CREATE_INFO [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_SET_CREATE_INFO [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_SPACE_CREATE_INFO [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_STATE_BOOLEAN [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_STATE_FLOAT [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_STATE_GET_INFO [

	^ self on: (58)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_STATE_POSE [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTION_STATE_VECTOR2F [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT [

	^ self on: (1000373000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB [

	^ self on: (1000070000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_API_LAYER_PROPERTIES [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BINDING_MODIFICATIONS_KHR [

	^ self on: (1000120000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINTS_LOCATE_INFO_BD [

	^ self on: (1000385002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB [

	^ self on: (1000076002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINTS_LOCATE_INFO_HTC [

	^ self on: (1000320002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINT_LOCATIONS_BD [

	^ self on: (1000385003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINT_LOCATIONS_FB [

	^ self on: (1000076005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_JOINT_LOCATIONS_HTC [

	^ self on: (1000320003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_SKELETON_FB [

	^ self on: (1000076006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_SKELETON_HTC [

	^ self on: (1000320004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_TRACKER_CREATE_INFO_BD [

	^ self on: (1000385001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_TRACKER_CREATE_INFO_FB [

	^ self on: (1000076001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BODY_TRACKER_CREATE_INFO_HTC [

	^ self on: (1000320001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BOUNDARY_2D_FB [

	^ self on: (1000175002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO [

	^ self on: (62)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COLOCATION_ADVERTISEMENT_START_INFO_META [

	^ self on: (1000571012)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COLOCATION_ADVERTISEMENT_STOP_INFO_META [

	^ self on: (1000571013)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COLOCATION_DISCOVERY_START_INFO_META [

	^ self on: (1000571010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COLOCATION_DISCOVERY_STOP_INFO_META [

	^ self on: (1000571011)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB [

	^ self on: (1000041001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR [

	^ self on: (1000034000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_CUBE_KHR [

	^ self on: (1000006000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR [

	^ self on: (1000017000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR [

	^ self on: (1000010000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB [

	^ self on: (1000212000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO [

	^ self on: (1000122000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR [

	^ self on: (1000091000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR [

	^ self on: (1000018000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB [

	^ self on: (1000040000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB [

	^ self on: (1000118003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC [

	^ self on: (1000317004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_PROJECTION [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW [

	^ self on: (48)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_QUAD [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT [

	^ self on: (1000066000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT [

	^ self on: (1000066001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB [

	^ self on: (1000072000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB [

	^ self on: (1000204000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB [

	^ self on: (1000171000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT [

	^ self on: (1000055000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT [

	^ self on: (1000055001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT [

	^ self on: (1000055003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT [

	^ self on: (1000055002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CONTROLLER_MODEL_STATE_MSFT [

	^ self on: (1000055004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_COORDINATE_SPACE_CREATE_INFO_ML [

	^ self on: (1000137000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_CREATE_SPATIAL_ANCHORS_COMPLETION_ML [

	^ self on: (1000140001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEBUG_UTILS_LABEL_EXT [

	^ self on: (1000019003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT [

	^ self on: (1000019001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT [

	^ self on: (1000019002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT [

	^ self on: (1000019000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEVICE_PCM_SAMPLE_RATE_GET_INFO_FB [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB [

	^ self on: (1000209002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE [

	^ self on: (1000196000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_HAND_REMOVAL_SET_INFO_META [

	^ self on: (1000291006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_ACQUIRE_INFO_META [

	^ self on: (1000291003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_META [

	^ self on: (1000291005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_VIEW_META [

	^ self on: (1000291004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_PROVIDER_CREATE_INFO_META [

	^ self on: (1000291000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_CREATE_INFO_META [

	^ self on: (1000291001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_STATE_META [

	^ self on: (1000291002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_BUFFER [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_COLOCATION_ADVERTISEMENT_COMPLETE_META [

	^ self on: (1000571022)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_COMPLETE_META [

	^ self on: (1000571025)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_RESULT_META [

	^ self on: (1000571024)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB [

	^ self on: (1000101000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_EVENTS_LOST [

	^ self on: (49)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_ML [

	^ self on: (1000472001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_ML [

	^ self on: (1000472000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED [

	^ self on: (52)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_ML [

	^ self on: (1000139001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX [

	^ self on: (1000033003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO [

	^ self on: (1000124001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_PASSTHROUGH_LAYER_RESUMED_META [

	^ self on: (1000282000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB [

	^ self on: (1000118030)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT [

	^ self on: (1000015000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB [

	^ self on: (1000198001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SHARE_SPACES_COMPLETE_META [

	^ self on: (1000290002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB [

	^ self on: (1000158107)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB [

	^ self on: (1000238001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB [

	^ self on: (1000156104)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB [

	^ self on: (1000156103)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB [

	^ self on: (1000158106)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB [

	^ self on: (1000113006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB [

	^ self on: (1000169002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB [

	^ self on: (1000113005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_START_COLOCATION_ADVERTISEMENT_COMPLETE_META [

	^ self on: (1000571020)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_START_COLOCATION_DISCOVERY_COMPLETE_META [

	^ self on: (1000571023)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_STOP_COLOCATION_ADVERTISEMENT_COMPLETE_META [

	^ self on: (1000571021)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_STOP_COLOCATION_DISCOVERY_COMPLETE_META [

	^ self on: (1000571026)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT [

	^ self on: (1000470000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META [

	^ self on: (1000219015)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META [

	^ self on: (1000219014)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META [

	^ self on: (1000219016)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META [

	^ self on: (1000219018)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META [

	^ self on: (1000219017)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR [

	^ self on: (1000031001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX [

	^ self on: (1000103001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EXTENSION_PROPERTIES [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EXTERNAL_CAMERA_OCULUS [

	^ self on: (1000226000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EYE_GAZES_FB [

	^ self on: (1000202003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EYE_GAZES_INFO_FB [

	^ self on: (1000202002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT [

	^ self on: (1000030001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_EYE_TRACKER_CREATE_INFO_FB [

	^ self on: (1000202001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_EXPRESSION_INFO2_FB [

	^ self on: (1000287015)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_EXPRESSION_INFO_FB [

	^ self on: (1000201002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB [

	^ self on: (1000287016)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB [

	^ self on: (1000201006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB [

	^ self on: (1000287014)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACE_TRACKER_CREATE_INFO_FB [

	^ self on: (1000201005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACIAL_EXPRESSIONS_HTC [

	^ self on: (1000104002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_GET_INFO_ML [

	^ self on: (1000482006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_PROPERTIES_ML [

	^ self on: (1000482007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACIAL_EXPRESSION_CLIENT_CREATE_INFO_ML [

	^ self on: (1000482005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC [

	^ self on: (1000104001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX [

	^ self on: (1000375001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO [

	^ self on: (1000121001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_APPLY_INFO_HTC [

	^ self on: (1000318000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC [

	^ self on: (1000318002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC [

	^ self on: (1000318001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META [

	^ self on: (1000200000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META [

	^ self on: (1000200001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB [

	^ self on: (1000115000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB [

	^ self on: (1000114000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_BEGIN_INFO [

	^ self on: (46)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_END_INFO [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_END_INFO_ML [

	^ self on: (1000135000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_STATE [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_SYNTHESIS_CONFIG_VIEW_EXT [

	^ self on: (1000211001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_SYNTHESIS_INFO_EXT [

	^ self on: (1000211000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FRAME_WAIT_INFO [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FUTURE_CANCEL_INFO_EXT [

	^ self on: (1000469000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FUTURE_COMPLETION_EXT [

	^ self on: (1000469002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FUTURE_POLL_INFO_EXT [

	^ self on: (1000469001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_FUTURE_POLL_RESULT_EXT [

	^ self on: (1000469003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB [

	^ self on: (1000118004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB [

	^ self on: (1000118005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_ML [

	^ self on: (1000136000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_D3D11_KHR [

	^ self on: (1000027000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_D3D12_KHR [

	^ self on: (1000028000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_EGL_MNDX [

	^ self on: (1000048004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_METAL_KHR [

	^ self on: (1000029000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR [

	^ self on: (1000024001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR [

	^ self on: (1000023003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR [

	^ self on: (1000023000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR [

	^ self on: (1000023002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR [

	^ self on: (1000023001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_VULKAN2_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR [

	^ self on: (1000025000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR [

	^ self on: (1000027002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR [

	^ self on: (1000028002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_METAL_KHR [

	^ self on: (1000029002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR [

	^ self on: (1000024003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR [

	^ self on: (1000023005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN2_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR [

	^ self on: (1000025002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT [

	^ self on: (1000051002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT [

	^ self on: (1000080000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_JOINT_LOCATIONS_EXT [

	^ self on: (1000051003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_JOINT_VELOCITIES_EXT [

	^ self on: (1000051004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_MESH_MSFT [

	^ self on: (1000052003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT [

	^ self on: (1000052001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT [

	^ self on: (1000052002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_POSE_TYPE_INFO_MSFT [

	^ self on: (1000052004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT [

	^ self on: (1000051001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_AIM_STATE_FB [

	^ self on: (1000111001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB [

	^ self on: (1000112000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT [

	^ self on: (1000428000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT [

	^ self on: (1000428001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_MESH_FB [

	^ self on: (1000110001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAND_TRACKING_SCALE_FB [

	^ self on: (1000110003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAPTIC_ACTION_INFO [

	^ self on: (59)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB [

	^ self on: (1000173001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAPTIC_PCM_VIBRATION_FB [

	^ self on: (1000209001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HAPTIC_VIBRATION [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT [

	^ self on: (1000063000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO [

	^ self on: (63)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INSTANCE_CREATE_INFO [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR [

	^ self on: (1000008000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INSTANCE_PROPERTIES [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE [

	^ self on: (1000079000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT [

	^ self on: (1000078000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INTERACTION_PROFILE_STATE [

	^ self on: (53)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING [

	^ self on: (51)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB [

	^ self on: (1000116009)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_KEYBOARD_TRACKING_QUERY_FB [

	^ self on: (1000116004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR [

	^ self on: (1000089000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_ML [

	^ self on: (1000139004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_ML [

	^ self on: (1000139003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_LOCALIZATION_MAP_ML [

	^ self on: (1000139000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META [

	^ self on: (1000216000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_ML [

	^ self on: (1000139002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_ML [

	^ self on: (1000138004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_ML [

	^ self on: (1000138002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_CREATE_INFO_ML [

	^ self on: (1000138001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML [

	^ self on: (1000138005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_SIZE_INFO_ML [

	^ self on: (1000138003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_ML [

	^ self on: (1000138006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_DETECTOR_STATE_ML [

	^ self on: (1000138007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_SPACE_CREATE_INFO_ML [

	^ self on: (1000138008)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO [

	^ self on: (1000124002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT [

	^ self on: (1000097002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB [

	^ self on: (1000118023)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_HTC [

	^ self on: (1000317002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META [

	^ self on: (1000266001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META [

	^ self on: (1000266002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META [

	^ self on: (1000266101)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META [

	^ self on: (1000266100)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB [

	^ self on: (1000118022)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB [

	^ self on: (1000118021)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_CREATE_INFO_FB [

	^ self on: (1000118001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC [

	^ self on: (1000317001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB [

	^ self on: (1000203002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB [

	^ self on: (1000118002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC [

	^ self on: (1000317003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_PREFERENCES_META [

	^ self on: (1000217000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PASSTHROUGH_STYLE_FB [

	^ self on: (1000118020)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PERFORMANCE_METRICS_COUNTER_META [

	^ self on: (1000232002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PERFORMANCE_METRICS_STATE_META [

	^ self on: (1000232001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT [

	^ self on: (1000429002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT [

	^ self on: (1000429001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT [

	^ self on: (1000429003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT [

	^ self on: (1000429004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_LOCATION_EXT [

	^ self on: (1000429005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT [

	^ self on: (1000429006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META [

	^ self on: (1000254001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META [

	^ self on: (1000254000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_REFERENCE_SPACE_CREATE_INFO [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RENDER_MODEL_BUFFER_FB [

	^ self on: (1000119002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB [

	^ self on: (1000119005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RENDER_MODEL_LOAD_INFO_FB [

	^ self on: (1000119003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RENDER_MODEL_PATH_INFO_FB [

	^ self on: (1000119000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_RENDER_MODEL_PROPERTIES_FB [

	^ self on: (1000119001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_ROOM_LAYOUT_FB [

	^ self on: (1000175001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB [

	^ self on: (1000198050)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT [

	^ self on: (1000097005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT [

	^ self on: (1000097007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_COMPONENTS_MSFT [

	^ self on: (1000097004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT [

	^ self on: (1000097006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT [

	^ self on: (1000097009)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_CREATE_INFO_MSFT [

	^ self on: (1000097001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT [

	^ self on: (1000098001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MARKERS_MSFT [

	^ self on: (1000147000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MARKER_QR_CODES_MSFT [

	^ self on: (1000147002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT [

	^ self on: (1000147001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESHES_MSFT [

	^ self on: (1000097013)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT [

	^ self on: (1000097014)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESH_BUFFERS_MSFT [

	^ self on: (1000097015)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT [

	^ self on: (1000097018)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT [

	^ self on: (1000097017)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT [

	^ self on: (1000097016)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_OBJECTS_MSFT [

	^ self on: (1000097008)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT [

	^ self on: (1000097010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT [

	^ self on: (1000097000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_PLANES_MSFT [

	^ self on: (1000097011)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT [

	^ self on: (1000097012)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT [

	^ self on: (1000053003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT [

	^ self on: (1000053002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT [

	^ self on: (1000053004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT [

	^ self on: (1000053000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT [

	^ self on: (1000053001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT [

	^ self on: (1000053005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SEMANTIC_LABELS_FB [

	^ self on: (1000175000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB [

	^ self on: (1000175010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT [

	^ self on: (1000098000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO [

	^ self on: (60)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SESSION_BEGIN_INFO [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SESSION_CREATE_INFO [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX [

	^ self on: (1000033000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SHARE_SPACES_INFO_META [

	^ self on: (1000290001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SHARE_SPACES_RECIPIENT_GROUPS_META [

	^ self on: (1000572000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACES_LOCATE_INFO_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB [

	^ self on: (1000156052)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_COMPONENT_STATUS_FB [

	^ self on: (1000113001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB [

	^ self on: (1000113007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_CONTAINER_FB [

	^ self on: (1000199000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_ERASE_INFO_FB [

	^ self on: (1000158001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_GROUP_UUID_FILTER_INFO_META [

	^ self on: (1000572001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_LIST_SAVE_INFO_FB [

	^ self on: (1000238000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_LOCATION [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_LOCATIONS_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_QUERY_INFO_FB [

	^ self on: (1000156001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_QUERY_RESULTS_FB [

	^ self on: (1000156002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_SAVE_INFO_FB [

	^ self on: (1000158000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_SHARE_INFO_FB [

	^ self on: (1000169001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB [

	^ self on: (1000156003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META [

	^ self on: (1000269001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_TRIANGLE_MESH_META [

	^ self on: (1000269002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_USER_CREATE_INFO_FB [

	^ self on: (1000241001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_UUID_FILTER_INFO_FB [

	^ self on: (1000156054)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_VELOCITIES_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPACE_VELOCITY [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_POSE_ML [

	^ self on: (1000140000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_UUIDS_ML [

	^ self on: (1000141003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_CREATE_STORAGE_INFO_ML [

	^ self on: (1000141000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_DETAILS_ML [

	^ self on: (1000141011)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_ML [

	^ self on: (1000141007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_DELETE_INFO_ML [

	^ self on: (1000141006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_DETAILS_ML [

	^ self on: (1000141010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_ML [

	^ self on: (1000141005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_PUBLISH_INFO_ML [

	^ self on: (1000141004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_QUERY_COMPLETION_ML [

	^ self on: (1000141002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_QUERY_INFO_RADIUS_ML [

	^ self on: (1000141001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_DETAILS_ML [

	^ self on: (1000141012)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_ML [

	^ self on: (1000141009)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_INFO_ML [

	^ self on: (1000141008)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB [

	^ self on: (1000113003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC [

	^ self on: (1000319001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT [

	^ self on: (1000039000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT [

	^ self on: (1000142001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT [

	^ self on: (1000142000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT [

	^ self on: (1000039001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_ANCHOR_STATE_ML [

	^ self on: (1000140002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT [

	^ self on: (1000049002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT [

	^ self on: (1000049003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT [

	^ self on: (1000049000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT [

	^ self on: (1000049001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_CREATE_INFO [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB [

	^ self on: (1000114001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO [

	^ self on: (55)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR [

	^ self on: (1000027001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR [

	^ self on: (1000028001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB [

	^ self on: (1000160000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_METAL_KHR [

	^ self on: (1000029001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR [

	^ self on: (1000024002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR [

	^ self on: (1000023004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO [

	^ self on: (57)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_VULKAN2_KHR [

	^ self on: (nil)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR [

	^ self on: (1000025001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO [

	^ self on: (56)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB [

	^ self on: (1000161000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB [

	^ self on: (1000114002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB [

	^ self on: (1000162000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB [

	^ self on: (1000163000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC [

	^ self on: (1000319000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_BD [

	^ self on: (1000385004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB [

	^ self on: (1000076004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_HTC [

	^ self on: (1000320000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_COLOCATION_DISCOVERY_PROPERTIES_META [

	^ self on: (1000571030)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB [

	^ self on: (1000108000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_ENVIRONMENT_DEPTH_PROPERTIES_META [

	^ self on: (1000291007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT [

	^ self on: (1000030000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB [

	^ self on: (1000202004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB [

	^ self on: (1000287013)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB [

	^ self on: (1000201004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FACIAL_EXPRESSION_PROPERTIES_ML [

	^ self on: (1000482004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC [

	^ self on: (1000104000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX [

	^ self on: (1000375000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO [

	^ self on: (1000121002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META [

	^ self on: (1000200002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_GET_INFO [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT [

	^ self on: (1000052000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT [

	^ self on: (1000051000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META [

	^ self on: (1000245000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB [

	^ self on: (1000116002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO [

	^ self on: (1000124000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML [

	^ self on: (1000138000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_NOTIFICATIONS_SET_INFO_ML [

	^ self on: (1000473000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META [

	^ self on: (1000266000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB [

	^ self on: (1000118006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB [

	^ self on: (1000118000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT [

	^ self on: (1000429007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_PROPERTIES [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB [

	^ self on: (1000119004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB [

	^ self on: (1000171001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_SPATIAL_ENTITY_GROUP_SHARING_PROPERTIES_META [

	^ self on: (1000572100)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB [

	^ self on: (1000113004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_SPATIAL_ENTITY_SHARING_PROPERTIES_META [

	^ self on: (1000290000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT [

	^ self on: (1000470001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META [

	^ self on: (1000219001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB [

	^ self on: (1000117001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_UNKNOWN [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_ML [

	^ self on: (1000472002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT [

	^ self on: (1000046000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_CONFIGURATION_PROPERTIES [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_CONFIGURATION_VIEW [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC [

	^ self on: (1000059000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO [

	^ self on: (1000121000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_LOCATE_INFO [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIEW_STATE [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META [

	^ self on: (1000219006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META [

	^ self on: (1000219002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META [

	^ self on: (1000219010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META [

	^ self on: (1000219004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META [

	^ self on: (1000219007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META [

	^ self on: (1000219005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META [

	^ self on: (1000219003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META [

	^ self on: (1000219009)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META [

	^ self on: (1000219011)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VISIBILITY_MASK_KHR [

	^ self on: (1000031000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT [

	^ self on: (1000097003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VIVE_TRACKER_PATHS_HTCX [

	^ self on: (1000103000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR [

	^ self on: (1000090001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR [

	^ self on: (1000090003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR [

	^ self on: (1000090000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META [

	^ self on: (1000227000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR [

	^ self on: (1000014000)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BLOCK_ML [

	^ self on: (1000474010)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BLOCK_REQUEST_ML [

	^ self on: (1000474008)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BLOCK_STATE_ML [

	^ self on: (1000474003)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BUFFER_ML [

	^ self on: (1000474007)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BUFFER_RECOMMENDED_SIZE_INFO_ML [

	^ self on: (1000474005)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_BUFFER_SIZE_ML [

	^ self on: (1000474006)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_DETECTOR_CREATE_INFO_ML [

	^ self on: (1000474001)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_GET_INFO_ML [

	^ self on: (1000474009)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_INFO_ML [

	^ self on: (1000474012)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_ML [

	^ self on: (1000474011)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_STATE_REQUEST_COMPLETION_ML [

	^ self on: (1000474004)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> XR_TYPE_WORLD_MESH_STATE_REQUEST_INFO_ML [

	^ self on: (1000474002)
]

{ #category : #'as yet unclassified' }
XrStructureType class >> originalTypeName [

    ^ 'long'
]
