Class {
	#name : #XrTrackingOptimizationSettingsDomainQCOM,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsDomainQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_DOMAIN_ALL_QCOM [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsDomainQCOM class >> originalTypeName [

    ^ 'long'
]
