Class {
	#name : #XrTrackingOptimizationSettingsHintQCOM,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_HINT_CLOSE_RANGE_PRIORIZATION_QCOM [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_HINT_HIGH_POWER_PRIORIZATION_QCOM [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_HINT_LONG_RANGE_PRIORIZATION_QCOM [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_HINT_LOW_POWER_PRIORIZATION_QCOM [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> XR_TRACKING_OPTIMIZATION_SETTINGS_HINT_NONE_QCOM [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrTrackingOptimizationSettingsHintQCOM class >> originalTypeName [

    ^ 'long'
]
