Class {
	#name : #XrVirtualKeyboardInputStateFlagBitsMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputStateFlagBitsMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_STATE_PRESSED_BIT_META [

	^ self on: (1 bitShift: 0)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputStateFlagBitsMETA class >> originalTypeName [

    ^ 'long'
]
