Class {
	#name : #XrVisibilityMaskTypeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrVisibilityMaskTypeKHR class >> XR_VISIBILITY_MASK_TYPE_HIDDEN_TRIANGLE_MESH_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrVisibilityMaskTypeKHR class >> XR_VISIBILITY_MASK_TYPE_LINE_LOOP_KHR [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrVisibilityMaskTypeKHR class >> XR_VISIBILITY_MASK_TYPE_VISIBLE_TRIANGLE_MESH_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrVisibilityMaskTypeKHR class >> originalTypeName [

    ^ 'long'
]
