Class {
	#name : #XrVirtualKeyboardLocationTypeMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrVirtualKeyboardLocationTypeMETA class >> XR_VIRTUAL_KEYBOARD_LOCATION_TYPE_CUSTOM_META [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardLocationTypeMETA class >> XR_VIRTUAL_KEYBOARD_LOCATION_TYPE_DIRECT_META [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardLocationTypeMETA class >> XR_VIRTUAL_KEYBOARD_LOCATION_TYPE_FAR_META [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardLocationTypeMETA class >> originalTypeName [

    ^ 'long'
]
