Class {
	#name : #XrVirtualKeyboardInputSourceMETA,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_CONTROLLER_DIRECT_LEFT_META [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_CONTROLLER_DIRECT_RIGHT_META [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_CONTROLLER_RAY_LEFT_META [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_CONTROLLER_RAY_RIGHT_META [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_HAND_DIRECT_INDEX_TIP_LEFT_META [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_HAND_DIRECT_INDEX_TIP_RIGHT_META [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_HAND_RAY_LEFT_META [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> XR_VIRTUAL_KEYBOARD_INPUT_SOURCE_HAND_RAY_RIGHT_META [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
XrVirtualKeyboardInputSourceMETA class >> originalTypeName [

    ^ 'long'
]
