Class {
	#name : #XrWorldMeshBlockStatusML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrWorldMeshBlockStatusML class >> XR_WORLD_MESH_BLOCK_STATUS_DELETED_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockStatusML class >> XR_WORLD_MESH_BLOCK_STATUS_NEW_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockStatusML class >> XR_WORLD_MESH_BLOCK_STATUS_UNCHANGED_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockStatusML class >> XR_WORLD_MESH_BLOCK_STATUS_UPDATED_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockStatusML class >> originalTypeName [

    ^ 'long'
]
