Class {
	#name : #XrWorldMeshBlockResultML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrWorldMeshBlockResultML class >> XR_WORLD_MESH_BLOCK_RESULT_FAILED_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockResultML class >> XR_WORLD_MESH_BLOCK_RESULT_PARTIAL_UPDATE_ML [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockResultML class >> XR_WORLD_MESH_BLOCK_RESULT_PENDING_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockResultML class >> XR_WORLD_MESH_BLOCK_RESULT_SUCCESS_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrWorldMeshBlockResultML class >> originalTypeName [

    ^ 'long'
]
