Class {
	#name : #XrWorldMeshDetectorLodML,
	#superclass : #ExternalTypeAlias,
	#category : #'OpenXR-Typedefs-Generated'
}

{ #category : #'as yet unclassified' }
XrWorldMeshDetectorLodML class >> XR_WORLD_MESH_DETECTOR_LOD_MAXIMUM_ML [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
XrWorldMeshDetectorLodML class >> XR_WORLD_MESH_DETECTOR_LOD_MEDIUM_ML [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
XrWorldMeshDetectorLodML class >> XR_WORLD_MESH_DETECTOR_LOD_MINIMUM_ML [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
XrWorldMeshDetectorLodML class >> originalTypeName [

    ^ 'long'
]
