Class {
	#name : #SRHandRayIntersectionResult,
	#superclass : #SRRayIntersectionResult,
	#instVars : [
		'actionState'
	],
	#category : #'SqueakXR-Collisions'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/8/2026 15:48'
}
SRHandRayIntersectionResult >> actionState [

	^ actionState
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/8/2026 15:49'
}
SRHandRayIntersectionResult >> actionState: state [

	actionState := state
]
