Class {
	#name : #SRPointIntersectionResult,
	#superclass : #Object,
	#instVars : [
		'point',
		'object',
		'distance'
	],
	#category : #'SqueakXR-Collisions'
}

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> distance [
	^ distance
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> distance: anObject [
	distance := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> object [
	^ object
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> object: anObject [
	object := anObject
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> point [
	^ point
]

{
	#category : #accessing,
	#'squeak_changestamp' : 'phkeese 9/15/2026 17:39'
}
SRPointIntersectionResult >> point: anObject [
	point := anObject
]
