Class {
	#name : #RlDefines,
	#superclass : #Object,
	#category : #'Raylib-Defines-Generated'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgb8Etc2 [
	""
	<generated>
	^ 37492
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbPvrtc4bppv1Img [
	""
	<generated>
	^ 35840
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbS3tcDxt1Ext [
	""
	<generated>
	^ 33776
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgba8Etc2Eac [
	""
	<generated>
	^ 37496
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaAstc4x4Khr [
	""
	<generated>
	^ 37808
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaAstc8x8Khr [
	""
	<generated>
	^ 37815
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaPvrtc4bppv1Img [
	""
	<generated>
	^ 35842
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaS3tcDxt1Ext [
	""
	<generated>
	^ 33777
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaS3tcDxt3Ext [
	""
	<generated>
	^ 33778
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glCompressedRgbaS3tcDxt5Ext [
	""
	<generated>
	^ 33779
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glEtc1Rgb8Oes [
	""
	<generated>
	^ 36196
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glLineWidth [
	""
	<generated>
	^ 2849
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glLuminance [
	""
	<generated>
	^ 6409
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glLuminanceAlpha [
	""
	<generated>
	^ 6410
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glMaxTextureMaxAnisotropyExt [
	""
	<generated>
	^ 34047
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glProgramPointSize [
	""
	<generated>
	^ 34370
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glShadingLanguageVersion [
	""
	<generated>
	^ 35724
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glTextureMaxAnisotropyExt [
	""
	<generated>
	^ 34046
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glUnsignedShort4444 [
	""
	<generated>
	^ 32819
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glUnsignedShort5551 [
	""
	<generated>
	^ 32820
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> glUnsignedShort565 [
	""
	<generated>
	^ 33635
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> raylibVersionMajor [
	""
	<generated>
	^ 5
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> raylibVersionMinor [
	""
	<generated>
	^ 6
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> raylibVersionPatch [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendColor [
	"GL_BLEND_COLOR"
	<generated>
	^ 32773
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendDstAlpha [
	"GL_BLEND_DST_ALPHA"
	<generated>
	^ 32970
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendDstRgb [
	"GL_BLEND_DST_RGB"
	<generated>
	^ 32968
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendEquation [
	"GL_BLEND_EQUATION"
	<generated>
	^ 32777
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendEquationAlpha [
	"GL_BLEND_EQUATION_ALPHA"
	<generated>
	^ 34877
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendEquationRgb [
	"GL_BLEND_EQUATION_RGB   // (Same as BLEND_EQUATION)"
	<generated>
	^ 32777
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendSrcAlpha [
	"GL_BLEND_SRC_ALPHA"
	<generated>
	^ 32971
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlBlendSrcRgb [
	"GL_BLEND_SRC_RGB"
	<generated>
	^ 32969
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlComputeShader [
	"GL_COMPUTE_SHADER"
	<generated>
	^ 37305
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlConstantAlpha [
	"GL_CONSTANT_ALPHA"
	<generated>
	^ 32771
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlConstantColor [
	"GL_CONSTANT_COLOR"
	<generated>
	^ 32769
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultBatchBufferElements [
	""
	<generated>
	^ 8192
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultBatchBuffers [
	"Default number of batch buffers (multi-buffering)"
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultBatchDrawcalls [
	"Default number of batch draw calls (by state changes: mode, texture)"
	<generated>
	^ 256
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultBatchMaxTextureUnits [
	"Maximum number of textures units that can be activated on batch drawing (SetShaderValueTexture())"
	<generated>
	^ 4
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationBoneids [
	""
	<generated>
	^ 7
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationBoneweights [
	""
	<generated>
	^ 8
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationColor [
	""
	<generated>
	^ 3
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationIndices [
	""
	<generated>
	^ 6
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationInstanceTx [
	""
	<generated>
	^ 9
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationNormal [
	""
	<generated>
	^ 2
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationPosition [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationTangent [
	""
	<generated>
	^ 4
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationTexcoord [
	""
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDefaultShaderAttribLocationTexcoord2 [
	""
	<generated>
	^ 5
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDrawFramebuffer [
	"GL_DRAW_FRAMEBUFFER"
	<generated>
	^ 36009
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDstAlpha [
	"GL_DST_ALPHA"
	<generated>
	^ 772
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDstColor [
	"GL_DST_COLOR"
	<generated>
	^ 774
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDynamicCopy [
	"GL_DYNAMIC_COPY"
	<generated>
	^ 35050
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDynamicDraw [
	"GL_DYNAMIC_DRAW"
	<generated>
	^ 35048
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlDynamicRead [
	"GL_DYNAMIC_READ"
	<generated>
	^ 35049
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlFloat [
	"GL_FLOAT"
	<generated>
	^ 5126
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlFragmentShader [
	"GL_FRAGMENT_SHADER"
	<generated>
	^ 35632
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlFuncAdd [
	"GL_FUNC_ADD"
	<generated>
	^ 32774
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlFuncReverseSubtract [
	"GL_FUNC_REVERSE_SUBTRACT"
	<generated>
	^ 32779
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlFuncSubtract [
	"GL_FUNC_SUBTRACT"
	<generated>
	^ 32778
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlLines [
	"GL_LINES"
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlMax [
	"GL_MAX"
	<generated>
	^ 32776
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlMaxMatrixStackSize [
	"Maximum size of Matrix stack"
	<generated>
	^ 32
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlMaxShaderLocations [
	"Maximum number of shader locations supported"
	<generated>
	^ 32
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlMin [
	"GL_MIN"
	<generated>
	^ 32775
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlModelview [
	"GL_MODELVIEW"
	<generated>
	^ 5888
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOne [
	"GL_ONE"
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusConstantAlpha [
	"GL_ONE_MINUS_CONSTANT_ALPHA"
	<generated>
	^ 32772
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusConstantColor [
	"GL_ONE_MINUS_CONSTANT_COLOR"
	<generated>
	^ 32770
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusDstAlpha [
	"GL_ONE_MINUS_DST_ALPHA"
	<generated>
	^ 773
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusDstColor [
	"GL_ONE_MINUS_DST_COLOR"
	<generated>
	^ 775
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusSrcAlpha [
	"GL_ONE_MINUS_SRC_ALPHA"
	<generated>
	^ 771
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlOneMinusSrcColor [
	"GL_ONE_MINUS_SRC_COLOR"
	<generated>
	^ 769
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlProjection [
	"GL_PROJECTION"
	<generated>
	^ 5889
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlQuads [
	"GL_QUADS"
	<generated>
	^ 7
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlReadFramebuffer [
	"GL_READ_FRAMEBUFFER"
	<generated>
	^ 36008
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlSrcAlpha [
	"GL_SRC_ALPHA"
	<generated>
	^ 770
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlSrcAlphaSaturate [
	"GL_SRC_ALPHA_SATURATE"
	<generated>
	^ 776
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlSrcColor [
	"GL_SRC_COLOR"
	<generated>
	^ 768
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStaticCopy [
	"GL_STATIC_COPY"
	<generated>
	^ 35046
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStaticDraw [
	"GL_STATIC_DRAW"
	<generated>
	^ 35044
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStaticRead [
	"GL_STATIC_READ"
	<generated>
	^ 35045
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStreamCopy [
	"GL_STREAM_COPY"
	<generated>
	^ 35042
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStreamDraw [
	"GL_STREAM_DRAW"
	<generated>
	^ 35040
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlStreamRead [
	"GL_STREAM_READ"
	<generated>
	^ 35041
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTexture [
	"GL_TEXTURE"
	<generated>
	^ 5890
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterAnisotropic [
	"Anisotropic filter (custom identifier)"
	<generated>
	^ 12288
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterLinear [
	"GL_LINEAR"
	<generated>
	^ 9729
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterLinearMipNearest [
	"GL_LINEAR_MIPMAP_NEAREST"
	<generated>
	^ 9985
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterMipLinear [
	"GL_LINEAR_MIPMAP_LINEAR"
	<generated>
	^ 9987
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterMipNearest [
	"GL_NEAREST_MIPMAP_NEAREST"
	<generated>
	^ 9984
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterNearest [
	"GL_NEAREST"
	<generated>
	^ 9728
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureFilterNearestMipLinear [
	"GL_NEAREST_MIPMAP_LINEAR"
	<generated>
	^ 9986
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureMagFilter [
	"GL_TEXTURE_MAG_FILTER"
	<generated>
	^ 10240
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureMinFilter [
	"GL_TEXTURE_MIN_FILTER"
	<generated>
	^ 10241
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureMipmapBiasRatio [
	"Texture mipmap bias, percentage ratio (custom identifier)"
	<generated>
	^ 16384
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapClamp [
	"GL_CLAMP_TO_EDGE"
	<generated>
	^ 33071
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapMirrorClamp [
	"GL_MIRROR_CLAMP_EXT"
	<generated>
	^ 34626
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapMirrorRepeat [
	"GL_MIRRORED_REPEAT"
	<generated>
	^ 33648
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapRepeat [
	"GL_REPEAT"
	<generated>
	^ 10497
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapS [
	"GL_TEXTURE_WRAP_S"
	<generated>
	^ 10242
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTextureWrapT [
	"GL_TEXTURE_WRAP_T"
	<generated>
	^ 10243
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlTriangles [
	"GL_TRIANGLES"
	<generated>
	^ 4
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlUnsignedByte [
	"GL_UNSIGNED_BYTE"
	<generated>
	^ 5121
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlVertexShader [
	"GL_VERTEX_SHADER"
	<generated>
	^ 35633
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 4/10/2026 17:40'
}
RlDefines class >> rlZero [
	"GL_ZERO"
	<generated>
	^ 0
]
