Class {
	#name : #AlDefines,
	#superclass : #Object,
	#category : #'OpenAL-Defines-Generated'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alBits [
	""
	<generated>
	^ 8194
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alBuffer [
	""
	<generated>
	^ 4105
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alBuffersProcessed [
	""
	<generated>
	^ 4118
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alBuffersQueued [
	""
	<generated>
	^ 4117
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alByteOffset [
	""
	<generated>
	^ 4134
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alChannels [
	""
	<generated>
	^ 8195
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alConeInnerAngle [
	""
	<generated>
	^ 4097
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alConeOuterAngle [
	""
	<generated>
	^ 4098
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alConeOuterGain [
	""
	<generated>
	^ 4130
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alDirection [
	""
	<generated>
	^ 4101
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alDistanceModel [
	""
	<generated>
	^ 53248
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alDopplerFactor [
	""
	<generated>
	^ 49152
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alDopplerVelocity [
	""
	<generated>
	^ 49153
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alExponentDistance [
	""
	<generated>
	^ 53253
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alExponentDistanceClamped [
	""
	<generated>
	^ 53254
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alExtensions [
	""
	<generated>
	^ 45060
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFalse [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFormatMono16 [
	""
	<generated>
	^ 4353
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFormatMono8 [
	""
	<generated>
	^ 4352
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFormatStereo16 [
	""
	<generated>
	^ 4355
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFormatStereo8 [
	""
	<generated>
	^ 4354
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alFrequency [
	""
	<generated>
	^ 8193
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alGain [
	""
	<generated>
	^ 4106
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInitial [
	""
	<generated>
	^ 4113
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInvalidEnum [
	""
	<generated>
	^ 40962
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInvalidName [
	""
	<generated>
	^ 40961
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInvalidOperation [
	""
	<generated>
	^ 40964
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInvalidValue [
	""
	<generated>
	^ 40963
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInverseDistance [
	""
	<generated>
	^ 53249
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alInverseDistanceClamped [
	""
	<generated>
	^ 53250
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alLinearDistance [
	""
	<generated>
	^ 53251
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alLinearDistanceClamped [
	""
	<generated>
	^ 53252
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alLooping [
	""
	<generated>
	^ 4103
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alMaxDistance [
	""
	<generated>
	^ 4131
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alMaxGain [
	""
	<generated>
	^ 4110
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alMinGain [
	""
	<generated>
	^ 4109
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alNoError [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alNone [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alOrientation [
	""
	<generated>
	^ 4111
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alOutOfMemory [
	""
	<generated>
	^ 40965
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alPaused [
	""
	<generated>
	^ 4115
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alPending [
	""
	<generated>
	^ 8209
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alPitch [
	""
	<generated>
	^ 4099
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alPlaying [
	""
	<generated>
	^ 4114
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alPosition [
	""
	<generated>
	^ 4100
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alProcessed [
	""
	<generated>
	^ 8210
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alReferenceDistance [
	""
	<generated>
	^ 4128
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alRenderer [
	""
	<generated>
	^ 45059
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alRolloffFactor [
	""
	<generated>
	^ 4129
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSampleOffset [
	""
	<generated>
	^ 4133
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSecOffset [
	""
	<generated>
	^ 4132
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSize [
	""
	<generated>
	^ 8196
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSourceRelative [
	""
	<generated>
	^ 514
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSourceState [
	""
	<generated>
	^ 4112
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSourceType [
	""
	<generated>
	^ 4135
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alSpeedOfSound [
	""
	<generated>
	^ 49155
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alStatic [
	""
	<generated>
	^ 4136
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alStopped [
	""
	<generated>
	^ 4116
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alStreaming [
	""
	<generated>
	^ 4137
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alTrue [
	""
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alUndetermined [
	""
	<generated>
	^ 4144
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alUnused [
	""
	<generated>
	^ 8208
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alVelocity [
	""
	<generated>
	^ 4102
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alVendor [
	""
	<generated>
	^ 45057
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alVersion [
	""
	<generated>
	^ 45058
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcAllAttributes [
	""
	<generated>
	^ 4099
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcAllDevicesSpecifier [
	""
	<generated>
	^ 4115
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcAttributesSize [
	""
	<generated>
	^ 4098
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcCaptureDefaultDeviceSpecifier [
	""
	<generated>
	^ 785
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcCaptureDeviceSpecifier [
	""
	<generated>
	^ 784
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcCaptureSamples [
	""
	<generated>
	^ 786
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcDefaultAllDevicesSpecifier [
	""
	<generated>
	^ 4114
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcDefaultDeviceSpecifier [
	""
	<generated>
	^ 4100
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcDeviceSpecifier [
	""
	<generated>
	^ 4101
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcEnumerateAllExt [
	""
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcExtCapture [
	""
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcExtensions [
	""
	<generated>
	^ 4102
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcFalse [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcFrequency [
	""
	<generated>
	^ 4103
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcInvalid [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcInvalidContext [
	""
	<generated>
	^ 40962
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcInvalidDevice [
	""
	<generated>
	^ 40961
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcInvalidEnum [
	""
	<generated>
	^ 40963
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcInvalidValue [
	""
	<generated>
	^ 40964
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcMajorVersion [
	""
	<generated>
	^ 4096
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcMinorVersion [
	""
	<generated>
	^ 4097
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcMonoSources [
	""
	<generated>
	^ 4112
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcNoError [
	""
	<generated>
	^ 0
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcOutOfMemory [
	""
	<generated>
	^ 40965
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcRefresh [
	""
	<generated>
	^ 4104
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcStereoSources [
	""
	<generated>
	^ 4113
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcSync [
	""
	<generated>
	^ 4105
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcTrue [
	""
	<generated>
	^ 1
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'lege 1/6/2026 17:46'
}
AlDefines class >> alcVersion01 [
	""
	<generated>
	^ 1
]
