name: create-release
on: workflow_dispatch
env:
  RELEASE_TIME: REPLACE-THIS
jobs:
  create-release-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - run: scripts/createRelease.sh
      - run: echo "RELEASE_TIME=$(date +%Y%m%d)" >> "$GITHUB_ENV"
      - uses: softprops/action-gh-release@v3
        with:
          tag-name: ${{ env.RELEASE_TIME }}-release
          files: *-SqueakXR-releaseImage.tar.gz
